### ISSUE TITLE
Compile failing due to ::fastrlp::RlpMacEncodedLen not implemented for trait bound `U256: MaxEncodedLenAssoc`

### ISSUE THREAD

**Issue by plotchy** [gio256/erigon-db#2]
I'm running into a compiler issue when attempting to import erigon-db into a project I'm working on. I'm new to Rust, so I'm probably missing something simple.

Cloning and running erigon-db from source with the following main.rs file leads to the code compiling and running as expected
```
git clone erigon-db
cd erigon-db
cargo run --bin erigon-db
```

```rust
// ./erigon-db/src/main.rs 
use erigon_db::{Erigon, env_open};
use ethereum_types::Address;
use std::fs::File;
use std::io::Write;
use std::io::LineWriter;

fn main() -> eyre::Result<()> {
    let path = std::path::Path::new(env!("ERIGON_CHAINDATA"));

    // Open an mdbx environment and begin a read-only database transaction
    let env = env_open(path)?;
    let db = Erigon::begin(&env)?;

    // get the current state of an account
    let contract: Address = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f".parse()?; //univ2factory
    let account = db.read_account(contract)?.unwrap();

    // write populated storage slots to file
    let file = File::create("output.txt")?;
    let mut file = LineWriter::new(file);

    for read in db.walk_storage(contract, account.incarnation, None)? {
        let (slot, value) = read?;
        file.write(format!("{}: {}\n", slot, value).as_bytes())?;
    }

    Ok(())
}
```

However, when I create a new cargo project and use erigon-db as a dependency:
```toml
# Cargo.toml
# --snip--
[dependencies]
erigon-db = {git = "https://github.com/gio256/erigon-db"}
ethers = { git = "https://github.com/gakonst/ethers-rs", optional = true }
```
I get the following error when running `cargo run`:

```
error[E0277]: the trait bound `U256: MaxEncodedLenAssoc` is not satisfied
   --> /home/plotchy/.cargo/git/checkouts/erigon-db-118ee4f05d317cb2/9b1347a/src/erigon/macros.rs:306:13
    |
306 |             ::fastrlp::RlpMaxEncodedLen,
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `MaxEncodedLenAssoc` is not implemented for `U256`
    |
   ::: /home/plotchy/.cargo/git/checkouts/erigon-db-118ee4f05d317cb2/9b1347a/src/erigon/models/transaction.rs:93:1
    |
93  | decl_u256_wrapper!(VPackChainId);
    | -------------------------------- in this macro invocation
    |
    = help: the following other types implement trait `MaxEncodedLenAssoc`:
              Bloom
              H128
              H160
              H256
              H512
              H520
              H64
              VPackChainId
            and 12 others
    = note: this error originates in the derive macro `::fastrlp::RlpMaxEncodedLen` (in Nightly builds, run with -Z macro-backtrace for more info)
```

It seems that the forked repo with the uint patches created in the `develop` branch of `gio256/fastrlp` is not being found?

**Comment by plotchy** [comment]
The issue is resolved with adding in more dependencies and patches within the Cargo.toml file

```toml
#Cargo.toml
[dependencies]
erigon-db = {git = "https://github.com/gio256/erigon-db"}
ethers = { git = "https://github.com/gakonst/ethers-rs", optional = true }
fastrlp = { version = "0.1", features = [
    "derive",
    "ethereum-types",
    "std",
] }
mdbx = { package = "libmdbx", version = "0.1.5" }
ethereum-types = { version = "0.13", features = ["codec"] }
eyre = "0.6.5"


[patch.crates-io]
libmdbx = { git = "https://github.com/gio256/libmdbx-rs", branch = "develop" }
fastrlp = { git = "https://github.com/gio256/fastrlp", branch = "develop" }
``` 

It now compiles and runs appropriately 👍️
